### ISSUE TITLE
or exactly I'm supposed to add this to index.js

### ISSUE THREAD

**Issue by Volubal** [GuriZenit/slash-bot-template#1]
```
const json = require('./options/commands.json')

client.api.applications(client.user.id)
    .guilds('928378990853492816')
    .commands.post({data: json['ADD']})
```

**Comment by guritso** [comment]
> ```
> const json = require('./options/commands.json')
> 
> client.api.applications(client.user.id)
>     .guilds('928378990853492816')
>     .commands.post({data: json['ADD']})
> ```

Inside of a ready event:

```js
client.on('ready', () => {
client.api.applications(client.user.id)
     .guilds('928378990853492816')
     .commands.post({data: json['ADD']})
})
```

Remember it only works on a old version of discord Js, 12.x only, the newest versions other methods are used

**Comment by guritso** [comment]
Check-out the new version updated to discord v14:
https://github.com/GuriZenit/slash-bot-template
