### ISSUE TITLE
Ephemeral [?]

### ISSUE THREAD

**Issue by mrc4tt** [GuriZenit/slash-bot-template#14]
Hi,

Is it possible to set "ephemeral: true" under the ping command? if so how shall it be set?

**Comment by guritso** [comment]
Yes, you just need do add it inside reply
```JavaScript 
  inter.reply({ 
    content: `${client.user.tag}: pong`,
    ephemeral: true,
  });

```

**Comment by mrc4tt** [comment]
@GuriZenit it worked. Would be nice, if it's the possible bot will "restart or reload" when there are changes from .js file e.g :-)

**Comment by guritso** [comment]
> @GuriZenit it worked. Would be nice, if it's the possible bot will "restart or reload" when there are changes from .js file e.g :-)

I'll look for it, thanks for the suggestion!
I need to add permissions too, if you have anyone else in your guild, he can use `add` and `delete` command, and that's a problem.

**Comment by mrc4tt** [comment]
> I'll look for it, thanks for the suggestion! I need to add permissions too, if have any other people in your guild, they can use `add` and `delete` command and that's a problem.

That's good to know! :+1:

**Comment by guritso** [comment]
> @GuriZenit it worked. Would be nice, if it's the possible bot will "restart or reload" when there are changes from .js file e.g :-)

You can clone de repo again and use it, [here](https://github.com/GuriZenit/slash-bot-template/pull/18) is a simple tutorial.
 It's a third-party package so I didn't have to do much

**Comment by guritso** [comment]
#21 fixes the error of using the package `nodemon` wich has been removed.
